print("This was added by Ronit")
print("This was added by Ronir")
print("This was added by Shubham")
print("This was added by Anonymous")
print("This was added by Mahesh")
print("This was added by sukesh")
print("This was added by Mahak Rawat.")